import { Category, PrismaClient } from '@prisma/client';
import bcrypt from 'bcrypt';

const prisma = new PrismaClient();
const load = async () => {
  const hashedPass = await bcrypt.hash('123', 10);
  try {
    await prisma.category.createMany({
      data: [
        {
          name: 'Терапевт',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Хирург',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Гениколог',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Паразитолог',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Дерматолог',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Кардиолог',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Онколог',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ] as Category[],
    });
    const spices = 'Собаки,Кошки,Лошади,Хорьки,Рептилии,Грызуны,Амфибии,Птицы,Экзотика,Беспозвоночные,Аквариумные рыбки,Сельскохозяйственные животные'.split(',');
    const spicesObjArr = spices
      .map((spice) => ({ name: spice, createdAt: new Date(), updatedAt: new Date() }));
    await prisma.profile.createMany({
      data: spicesObjArr,
    });
    await prisma.userGroup.createMany({
      data: [
        {
          name: 'Врач',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Владелец животного',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
    });
    await prisma.user.createMany({
      data: [
        {
          name: 'Георгий Цамаладзе',
          email: 'tsamaladze@gmail.com',
          phone: '89999873077',
          password: hashedPass,
          userGroupId: 2,
          img: 'george.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Юля Тен',
          email: 'u10@gmail.com',
          phone: '89999871488',
          password: hashedPass,
          userGroupId: 1,
          img: 'ten.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
    });
    await prisma.categoryOnUser.createMany({
      data: [
        {
          docId: 2,
          categoryId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 2,
          categoryId: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 2,
          categoryId: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
    });
    await prisma.profileOnUser.createMany({
      data: [
        {
          docId: 2,
          profileId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 2,
          profileId: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 2,
          profileId: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
    });
    await prisma.pet.createMany({
      data: [
        {
          name: 'Бобик',
          specie: 'собака',
          breed: 'лайка',
          sex: 1,
          birthday: new Date(Date.parse('2019-09-14 00:00')),
          weight: 3.40,
          color: 'Белый',
          sterilized: true,
          sterilizedDate: new Date(Date.parse('2020-10-14 00:00')),
          ownerId: 1,
          img: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
    });
    await prisma.chronicDiseases.createMany({
      data: [
        {
          petId: 1,
          name: 'Ринит',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
    });
    await prisma.vaccination.createMany({
      data: [
        {
          petId: 1,
          drugName: 'РАБИКС',
          drugDate: new Date(Date.parse('2020-12-11 00:00')),
          description: 'вакцинация против бешенства',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          petId: 1,
          drugName: 'МУЛЬТИКАН-8',
          drugDate: new Date(Date.parse('2021-10-12 00:00')),
          description: 'Вакцина против чумы',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
    });
    await prisma.allergy.createMany({
      data: [
        {
          petId: 1,
          name: 'Аллергия на рыбу',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          petId: 1,
          name: 'Аллергия на молоко',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          petId: 1,
          name: 'Аллергия на солнце',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
    });
    await prisma.visit.createMany({
      data: [
        {
          docId: 2,
          userId: 1,
          petId: 1,
          visitDate: new Date(Date.parse('2021-10-12 00:00')),
          description: 'Жалобы на тяжелое дыхание',
          diagnose: 'Хронический насморк',
          treatment:
            'Капли назальные для собак, 3 раза в день, в течении 7 дней.',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 2,
          userId: 1,
          petId: 1,
          visitDate: new Date(Date.parse('2022-04-14 00:00')),
          description: 'Жалобы на выделения из глаз',
          diagnose: 'Инфекционное заражение слезных мешочков',
          treatment:
            'Капли глазные для собак, 3 раза в день, в течении 2 дней.',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
    });
    await prisma.docSchedules.createMany({
      data: [
        {
          docId: 2,
          userId: 1,
          petId: 1,
          dateOfReceipt: new Date(2022, 8, 1, 15, 40),
          isClose: false,
          createdAt: new Date(Date.parse('2022-08-01 00:00')),
          updatedAt: new Date(Date.parse('2022-08-01 00:00')),
        },
        {
          docId: 2,
          userId: 1,
          petId: 1,
          dateOfReceipt: new Date(2022, 8, 1, 16, 0),
          isClose: false,
          createdAt: new Date(Date.parse('2022-08-01 00:00')),
          updatedAt: new Date(Date.parse('2022-08-01 00:00')),
        },
      ],
    });
    await prisma.user.createMany({
      data: [
        {
          name: 'Александр Князев',
          email: 'alexander.knyazev@elbrusboot.camp',
          phone: '89953345214',
          password: hashedPass,
          userGroupId: 1,
          img: 'alexander.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Артем Оганесян',
          email: 'artiom.oganesyan@elbrusboot.camp',
          phone: '85472319945',
          password: hashedPass,
          userGroupId: 1,
          img: 'artyom.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Дарсен Унгарлинов',
          email: 'ungarlinov.darsen@elbrusboot.camp',
          phone: '897654342213',
          password: hashedPass,
          userGroupId: 1,
          img: 'darsen.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Мовсар Махмутов',
          email: 'mahmutov.movsar@elbrusboot.camp',
          phone: '89348729365',
          password: hashedPass,
          userGroupId: 1,
          img: 'movsar.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Адам Балкоев',
          email: 'adam.balkoev@elbrusboot.camp',
          phone: '89784951156',
          password: hashedPass,
          userGroupId: 1,
          img: 'adam.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Антон Панферов',
          email: 'anton.panferov@elbrusboot.camp',
          phone: '89657876331',
          password: hashedPass,
          userGroupId: 1,
          img: 'anton.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Кирилл Кукулиев',
          email: 'kirill.kukuliev@elbrusboot.camp',
          phone: '89842367745',
          password: hashedPass,
          userGroupId: 1,
          img: 'kirill.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Сергей Дочкин',
          email: 'sergei.dochkin@elbrusboot.camp',
          phone: '89764548852',
          password: hashedPass,
          userGroupId: 1,
          img: 'sergei.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Юлия Тарасова',
          email: 'ju@elbrusboot.camp',
          phone: '89836128843',
          password: hashedPass,
          userGroupId: 1,
          img: 'ju.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Георгий Бабаян',
          email: 'george@elbrusboot.camp',
          phone: '89175593411',
          password: hashedPass,
          userGroupId: 1,
          img: 'babayan.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Баяр Малханов',
          email: 'bayarik@bk.ru',
          phone: '89246566651',
          password: hashedPass,
          userGroupId: 2,
          img: 'bayartes.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Марина Абрамова',
          email: 'kikkafikka90@gmail.com',
          phone: '89148762398',
          password: hashedPass,
          userGroupId: 2,
          img: 'marina.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
    });
    await prisma.categoryOnUser.createMany({
      data: [
        {
          docId: 3,
          categoryId: 7,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 3,
          categoryId: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 4,
          categoryId: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 4,
          categoryId: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 5,
          categoryId: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 5,
          categoryId: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 6,
          categoryId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 6,
          categoryId: 7,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 7,
          categoryId: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 7,
          categoryId: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 8,
          categoryId: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 8,
          categoryId: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 9,
          categoryId: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 9,
          categoryId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 10,
          categoryId: 7,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 10,
          categoryId: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 11,
          categoryId: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 11,
          categoryId: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 12,
          categoryId: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 12,
          categoryId: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 12,
          categoryId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
    });
    await prisma.profileOnUser.createMany({
      data: [
        {
          docId: 3,
          profileId: 12,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 3,
          profileId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 3,
          profileId: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 4,
          profileId: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 4,
          profileId: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 4,
          profileId: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 5,
          profileId: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 5,
          profileId: 7,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 5,
          profileId: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 6,
          profileId: 9,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 6,
          profileId: 10,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 6,
          profileId: 11,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 7,
          profileId: 12,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 7,
          profileId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 7,
          profileId: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 8,
          profileId: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 8,
          profileId: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 8,
          profileId: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 9,
          profileId: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 9,
          profileId: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 9,
          profileId: 7,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 9,
          profileId: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 10,
          profileId: 9,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 10,
          profileId: 10,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 10,
          profileId: 11,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 11,
          profileId: 12,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 11,
          profileId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 11,
          profileId: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 12,
          profileId: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 12,
          profileId: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 12,
          profileId: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
    });
    await prisma.pet.createMany({
      data: [
        {
          name: 'Марс',
          specie: 'кот',
          breed: 'Без породы',
          sex: 1,
          birthday: new Date(Date.parse('2013-04-05 00:00')),
          weight: 4.3,
          color: 'Черный',
          sterilized: true,
          sterilizedDate: new Date(Date.parse('2014-02-14 00:00')),
          ownerId: 13,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Рубик',
          specie: 'Амфибия',
          breed: 'Без породы',
          sex: 1,
          birthday: new Date(Date.parse('2020-07-16 00:00')),
          weight: 0.2,
          color: 'Черный',
          sterilized: false,
          ownerId: 13,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Акра',
          specie: 'собака',
          breed: 'колли',
          sex: 0,
          birthday: new Date(Date.parse('2018-02-10 00:00')),
          weight: 6.84,
          color: 'Коричневый',
          sterilized: true,
          sterilizedDate: new Date(Date.parse('2019-02-23 00:00')),
          ownerId: 14,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Посейдон',
          specie: 'Аквариумная рыбка',
          breed: 'гуппи',
          sex: 1,
          birthday: new Date(Date.parse('2021-07-12 00:00')),
          weight: 0.08,
          color: 'Красный',
          sterilized: false,
          ownerId: 14,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
    });
    await prisma.chronicDiseases.createMany({
      data: [
        {
          petId: 2,
          name: 'Панкреатит',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          petId: 3,
          name: 'Ринит',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          petId: 4,
          name: 'Аденовироз',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          petId: 5,
          name: 'Колумнарис',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
    });
    await prisma.vaccination.createMany({
      data: [
        {
          petId: 2,
          drugName: 'РАБИКС',
          drugDate: new Date(Date.parse('2014-06-11 00:00')),
          description: 'вакцинация против бешенства',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          petId: 3,
          drugName: 'РЕПТИЛАЙФ',
          drugDate: new Date(Date.parse('2021-02-10 00:00')),
          description: 'Суспензия антигельминтик для рептилий',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          petId: 4,
          drugName: 'МУЛЬТИКАН-8',
          drugDate: new Date(Date.parse('2019-09-12 00:00')),
          description: 'Вакцина против чумы',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          petId: 5,
          drugName: 'Бактопур',
          drugDate: new Date(Date.parse('2021-11-18 00:00')),
          description: 'Ванна против колумнариса(гниение рта)',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
    });
    await prisma.visit.createMany({
      data: [
        {
          docId: 12,
          userId: 13,
          petId: 2,
          visitDate: new Date(Date.parse('2014-06-11 00:00')),
          description: 'Плановое обследование',
          diagnose: 'Плановое обследование - вакцинация',
          treatment:
            'Состояние здоровья удовлетворительное - поставлена вакцина РАБИКС',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 4,
          userId: 13,
          petId: 2,
          visitDate: new Date(Date.parse('2018-10-01 00:00')),
          description: 'Прихрамывание на левую лапу',
          diagnose: 'Рана передней левой лапы',
          treatment:
            'Промывание раны раствором хлоргексидина 0.05%',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 5,
          userId: 13,
          petId: 3,
          visitDate: new Date(Date.parse('2021-02-10 00:00')),
          description: 'Жалобы на стул с гельминтами',
          diagnose: 'Заражение гельминтами',
          treatment:
            'Суспензия антигельминтик для рептилий, 1 раза в день, в течении 3 дней.',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 6,
          userId: 13,
          petId: 3,
          visitDate: new Date(Date.parse('2021-02-10 00:00')),
          description: 'Жалобы на чейшуйки с мутной жидкостью',
          diagnose: 'Дерматомикозы',
          treatment:
            'Купать в растворе малахитовой зелени из расчета 0,15 миллиграмм на 1 литр в течение 15 минут. Процедуру проводят 3 дня подряд',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 7,
          userId: 14,
          petId: 4,
          visitDate: new Date(Date.parse('2018-02-10 00:00')),
          description: 'Жалобы на тяжелое дыхание',
          diagnose: 'Хронический ринит',
          treatment:
            'Капли назальные для собак, 3 раза в день, в течении 7 дней.',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 8,
          userId: 14,
          petId: 4,
          visitDate: new Date(),
          description: 'Жалобы на кашель',
          diagnose: 'Парагрипп',
          treatment:
            'Повышение влажности в среде обитания питомца',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 9,
          userId: 14,
          petId: 5,
          visitDate: new Date(Date.parse('2021-11-18 00:00')),
          description: 'Снижение активности у рыбки',
          diagnose: 'Гниение рта',
          treatment:
            'Бактопур - 1 раз в день в течении 10 минут (5 дней) Ванна против колумнариса(гниение рта)',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 10,
          userId: 14,
          petId: 5,
          visitDate: new Date(Date.parse('2021-12-28 00:00')),
          description: 'Потемнение жабр, снижение активности рыбки',
          diagnose: 'Сапролегниоз',
          treatment:
            'в общем аквариуме применяется стрептоцид, бициллин-5, в отдельной ёмкости - соль, сульфат меди (осторожно, при неправильной дозировке нанесет рыбе вред). Легко предотвратить, если содержать аквариум в чистоте.',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
    });
    await prisma.docInfo.createMany({
      data: [
        {
          docId: 2,
          experience: 'Люблю свою работу. Берусь за самые сложные случаи. "Если нельзя вылечить, это не значит, что нельзя помочь"',
          clinicAddress: 'г. Москва, Проспект вернадского, 43, кв 29',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 3,
          experience: 'Рад стать лечащим врачом для вашего любимого питомца. Опыт работы в Ветеринарии 13 лет! Выезжаю на дом. Москва и ближнее Подмосковье. Также предоставляю консультации по телефону!',
          clinicAddress: 'г. Москва, Шоссейный проезд, 43, офис 9',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 4,
          experience: 'Очень легко нахожу контакт с животными и их владельцами. Большой опыт терапевтического и хирургического приема. «Лучшие врачи в мире являются ветеринарами. Они не могут спросить пациента в чем дело — они должны просто знать» Уилл Роджерс. Я практикующий ветеринарный врач с высшим образованием и опытом работы 13 лет. Никогда не прекращаю свое обучение! Читаю о новейших достижениях ветеринарии, участвую в конференциях, прохожу стажировки, знаю английский язык.',
          clinicAddress: 'г. Москва, Шувалова , 43, офис 9',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 5,
          experience: 'Люблю свою работу и пациентов, с уважением отношусь к их владельцам. Главные принципы моей работы: Безопасность и эффективность процедур. Соблюдение протоколов, разработанных ведущими мировыми ветеринарными специалистами. Назначение современных препаратов с доказанной эффективностью. Своевременное проведение необходимой диагностики.',
          clinicAddress: 'г. Москва, Шухова , 42, офис 2',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 6,
          experience: 'Общий опыт работы ветеринарным врачом более 17 лет, врач высшей категории, член Гильдии ветеринарных врачей г. Москвы. Аспирант кафедры морфологии, патологии животных и биологии СГАУ им. Н. И. Вавилова.',
          clinicAddress: 'г. Москва, Фадеева , 4, офис 923',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 7,
          experience: 'Грамотно, индивидуально, ответственно подхожу к каждому животному, стараюсь в лечение причинить меньше стресса.  Делаю операции любой сложности! Люблю животных и никогда не бросаю лечение на половине пути, всегда довожу дело до конца. Провожу стерилизацию кошек и собак только на импортном наркозе, косметические швы, которые не требуют обработок и снятия.',
          clinicAddress: 'г. Москва, Ленина , 32, офис 12',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 8,
          experience: 'Наши питомцы дают нам намного больше, чем мы можем дать им взамен.  Онлайн консультации.  передержка мелких экзотических животных.  Здравствуйте! Сказать честно в детстве не думал, что могу стать ветеринаром. Но человек предполагает — Б-г располагает. Первая моя практика, началось в 2008 году. И с первых дней, я попал на работу к ведущим специалистам в ветеринарии, некоторые из них были мои преподаватели в университете. Только со временем я понял насколько важно иметь хороших учителей в начале своей профессии. Я думаю, что иметь в семье кота, или собаку, или попугая (пускай и слишком крикливого), или кого-то ещё — это большое благо для всех её членов. Даже если до конца не каждый это понимает. Наши питомца в этом круговороте жизни дают нам намного больше, чем мы можем дать им.',
          clinicAddress: 'г. Москва, Орджоникидзе , 10, строение 10',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 9,
          experience: 'Специализируюсь на услугах на дому у кошек, как стрессовых животных (УЗИ, анализы, вакцинация, манипуляции, операции).  Часто кошки очень привязаны к дому и сильно стрессуют, если их пытаются из дома вынести, например, в клинику. В подобной ситуации можно вызвать врача на дом, чтобы свести переживания животного к минимуму.',
          clinicAddress: 'г. Москва, Ферсмана , 87, офис 76',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 10,
          experience: 'Ветеринарный врач общей практики. Опыт работы в клинике более 8 лет, широкая практика в разных специализациях ветеринарии.Помимо практической лечебной деятельности пишу кандидатскую диссертацию. Буду для вас «своим» ветврачом, к которому всегда можно обратиться Мой подход к работе разумный! Говорю честно и по делу. Не назначаю не нужных препаратов, например Гомеопатии! Лишние уколы, таблетки ни к чему! Могу аргументировать любое свое действие и назначенный препарат.',
          clinicAddress: 'г. Москва, Венецианская , 23, офис 49',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 11,
          experience: 'С любовью отношусь к животным, ответственна, внимательна, пунктуальна. Постоянно повышаю свою квалификацию и обучаюсь на курсах постдипломного образования, специализируюсь на дерматологии собак и кошек, веду терапевтический прием. Руководствуюсь принципами доказательной медицины, не использую гомеопатию и препараты с недоказанной эффективностью. Дерматологические пациенты требуют длительного мониторинга и лечения; я всегда стараюсь быть на связи со своими клиентами, чтобы поставить диагноз и вылечить подопечных. Довольно мобильна-выезжаю на дом в Москву и по области: Нахабино, Красногорск, Митино, Павловская Слобода и другие близлежащие населённые пункты. Буду рада Вам помочь!',
          clinicAddress: 'г. Москва, Очаковская , 13, офис 56',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 12,
          experience: 'О себе  Выезжаю на дом и принимаю в кабинете на Тверской.  Опыт работы с домашними животными более четырёх лет. Являюсь ежегодным участником научных ветеринарных конференций (NVC, Purina Pro Plan) Постоянно учусь и развиваюсь. Обожаю четвероногих друзей!)',
          clinicAddress: 'г. Москва, Заречная , 45, офис 92',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
    });
    await prisma.priceList.createMany({
      data: [
        {
          docId: 2,
          service: 'Ветеринарная терапия: осмотр, консультация, составление схемы лечения',
          price: 1500,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 2,
          service: 'УЗИ для животных',
          price: 1000,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 2,
          service: 'Анализы у животных (Работаю с лабораториями ШансБио, НеоВет и Зайцев+)',
          price: 1500,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 2,
          service: 'Иксодовые клещи',
          price: 500,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 2,
          service: 'Вакцинация животных',
          price: 2000,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 2,
          service: 'Ветеринарная стоматология',
          price: 5000,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 3,
          service: 'Ветеринарная терапия: осмотр, консультация, составление схемы лечения',
          price: 1500,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 3,
          service: 'УЗИ для животных',
          price: 1000,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 3,
          service: 'Анализы у животных (Работаю с лабораториями ШансБио, НеоВет и Зайцев+)',
          price: 1500,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 3,
          service: 'Иксодовые клещи',
          price: 500,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 3,
          service: 'Вакцинация животных',
          price: 2000,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 3,
          service: 'Ветеринарная стоматология',
          price: 5000,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 4,
          service: 'Ветеринарная терапия: осмотр, консультация, составление схемы лечения',
          price: 1500,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 4,
          service: 'УЗИ для животных',
          price: 1000,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 4,
          service: 'Анализы у животных (Работаю с лабораториями ШансБио, НеоВет и Зайцев+)',
          price: 1500,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 4,
          service: 'Иксодовые клещи',
          price: 500,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 4,
          service: 'Вакцинация животных',
          price: 2000,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 4,
          service: 'Ветеринарная стоматология',
          price: 5000,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 5,
          service: 'Ветеринарная терапия: осмотр, консультация, составление схемы лечения',
          price: 1500,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 5,
          service: 'УЗИ для животных',
          price: 1000,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 5,
          service: 'Анализы у животных (Работаю с лабораториями ШансБио, НеоВет и Зайцев+)',
          price: 1500,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 5,
          service: 'Иксодовые клещи',
          price: 500,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 5,
          service: 'Вакцинация животных',
          price: 2000,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 5,
          service: 'Ветеринарная стоматология',
          price: 5000,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 6,
          service: 'Ветеринарная терапия: осмотр, консультация, составление схемы лечения',
          price: 1500,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 6,
          service: 'УЗИ для животных',
          price: 1000,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 6,
          service: 'Анализы у животных (Работаю с лабораториями ШансБио, НеоВет и Зайцев+)',
          price: 1500,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 6,
          service: 'Иксодовые клещи',
          price: 500,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 6,
          service: 'Вакцинация животных',
          price: 2000,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 6,
          service: 'Ветеринарная стоматология',
          price: 5000,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 7,
          service: 'Ветеринарная терапия: осмотр, консультация, составление схемы лечения',
          price: 1500,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 7,
          service: 'УЗИ для животных',
          price: 1000,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 7,
          service: 'Анализы у животных (Работаю с лабораториями ШансБио, НеоВет и Зайцев+)',
          price: 1500,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 7,
          service: 'Иксодовые клещи',
          price: 500,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 7,
          service: 'Вакцинация животных',
          price: 2000,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 7,
          service: 'Ветеринарная стоматология',
          price: 5000,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 8,
          service: 'Ветеринарная терапия: осмотр, консультация, составление схемы лечения',
          price: 1500,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 8,
          service: 'УЗИ для животных',
          price: 1000,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 8,
          service: 'Анализы у животных (Работаю с лабораториями ШансБио, НеоВет и Зайцев+)',
          price: 1500,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 8,
          service: 'Иксодовые клещи',
          price: 500,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 8,
          service: 'Вакцинация животных',
          price: 2000,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 8,
          service: 'Ветеринарная стоматология',
          price: 5000,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 9,
          service: 'Ветеринарная терапия: осмотр, консультация, составление схемы лечения',
          price: 1500,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 9,
          service: 'УЗИ для животных',
          price: 1000,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 9,
          service: 'Анализы у животных (Работаю с лабораториями ШансБио, НеоВет и Зайцев+)',
          price: 1500,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 9,
          service: 'Иксодовые клещи',
          price: 500,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 9,
          service: 'Вакцинация животных',
          price: 2000,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 9,
          service: 'Ветеринарная стоматология',
          price: 5000,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 10,
          service: 'Ветеринарная терапия: осмотр, консультация, составление схемы лечения',
          price: 1500,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 10,
          service: 'УЗИ для животных',
          price: 1000,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 10,
          service: 'Анализы у животных (Работаю с лабораториями ШансБио, НеоВет и Зайцев+)',
          price: 1500,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 10,
          service: 'Иксодовые клещи',
          price: 500,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 10,
          service: 'Вакцинация животных',
          price: 2000,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 10,
          service: 'Ветеринарная стоматология',
          price: 5000,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 11,
          service: 'Ветеринарная терапия: осмотр, консультация, составление схемы лечения',
          price: 1500,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 11,
          service: 'УЗИ для животных',
          price: 1000,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 11,
          service: 'Анализы у животных (Работаю с лабораториями ШансБио, НеоВет и Зайцев+)',
          price: 1500,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 11,
          service: 'Иксодовые клещи',
          price: 500,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 11,
          service: 'Вакцинация животных',
          price: 2000,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 11,
          service: 'Ветеринарная стоматология',
          price: 5000,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 12,
          service: 'Ветеринарная терапия: осмотр, консультация, составление схемы лечения',
          price: 1500,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 12,
          service: 'УЗИ для животных',
          price: 1000,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 12,
          service: 'Анализы у животных (Работаю с лабораториями ШансБио, НеоВет и Зайцев+)',
          price: 1500,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 12,
          service: 'Иксодовые клещи',
          price: 500,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 12,
          service: 'Вакцинация животных',
          price: 2000,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          docId: 12,
          service: 'Ветеринарная стоматология',
          price: 5000,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
    });
    await prisma.docSchedules.createMany({
      data: [
        {
          docId: 11,
          userId: 1,
          petId: 1,
          dateOfReceipt: '2022-08-05T12:00:00.000+03:00',
          isClose: false,
          createdAt: new Date(Date.parse('2022-08-01 00:00')),
          updatedAt: new Date(Date.parse('2022-08-01 00:00')),
        },
        {
          docId: 11,
          userId: 13,
          petId: 2,
          dateOfReceipt: new Date(2022, 7, 5, 10, 0),
          isClose: false,
          createdAt: new Date(Date.parse('2022-08-01 00:00')),
          updatedAt: new Date(Date.parse('2022-08-01 00:00')),
        },
        {
          docId: 11,
          userId: 13,
          petId: 3,
          dateOfReceipt: new Date(2022, 7, 5, 10, 30),
          isClose: false,
          createdAt: new Date(Date.parse('2022-08-01 00:00')),
          updatedAt: new Date(Date.parse('2022-08-01 00:00')),
        },
        {
          docId: 11,
          userId: 14,
          petId: 4,
          dateOfReceipt: new Date(2022, 7, 5, 11, 0),
          isClose: false,
          createdAt: new Date(Date.parse('2022-08-01 00:00')),
          updatedAt: new Date(Date.parse('2022-08-01 00:00')),
        },
        {
          docId: 11,
          userId: 14,
          petId: 5,
          dateOfReceipt: new Date(2022, 7, 5, 16, 0),
          isClose: false,
          createdAt: new Date(Date.parse('2022-08-01 00:00')),
          updatedAt: new Date(Date.parse('2022-08-01 00:00')),
        },
        {
          docId: 11,
          userId: 1,
          petId: 1,
          dateOfReceipt: new Date(2022, 7, 8, 9, 0),
          isClose: false,
          createdAt: new Date(Date.parse('2022-08-01 00:00')),
          updatedAt: new Date(Date.parse('2022-08-01 00:00')),
        },
        {
          docId: 11,
          userId: 13,
          petId: 2,
          dateOfReceipt: new Date(2022, 7, 8, 10, 0),
          isClose: false,
          createdAt: new Date(Date.parse('2022-08-01 00:00')),
          updatedAt: new Date(Date.parse('2022-08-01 00:00')),
        },
        {
          docId: 11,
          userId: 13,
          petId: 3,
          dateOfReceipt: new Date(2022, 7, 8, 10, 30),
          isClose: false,
          createdAt: new Date(Date.parse('2022-08-01 00:00')),
          updatedAt: new Date(Date.parse('2022-08-01 00:00')),
        },
        {
          docId: 11,
          userId: 14,
          petId: 4,
          dateOfReceipt: new Date(2022, 7, 8, 11, 0),
          isClose: false,
          createdAt: new Date(Date.parse('2022-08-01 00:00')),
          updatedAt: new Date(Date.parse('2022-08-01 00:00')),
        },
        {
          docId: 11,
          userId: 14,
          petId: 5,
          dateOfReceipt: new Date(2022, 7, 8, 16, 0),
          isClose: false,
          createdAt: new Date(Date.parse('2022-08-01 00:00')),
          updatedAt: new Date(Date.parse('2022-08-01 00:00')),
        },
        {
          docId: 11,
          userId: 1,
          petId: 1,
          dateOfReceipt: new Date(2022, 7, 9, 9, 0),
          isClose: false,
          createdAt: new Date(Date.parse('2022-08-01 00:00')),
          updatedAt: new Date(Date.parse('2022-08-01 00:00')),
        },
        {
          docId: 11,
          userId: 13,
          petId: 2,
          dateOfReceipt: new Date(2022, 7, 9, 10, 0),
          isClose: false,
          createdAt: new Date(Date.parse('2022-08-01 00:00')),
          updatedAt: new Date(Date.parse('2022-08-01 00:00')),
        },
        {
          docId: 11,
          userId: 13,
          petId: 3,
          dateOfReceipt: new Date(2022, 7, 9, 10, 30),
          isClose: false,
          createdAt: new Date(Date.parse('2022-08-01 00:00')),
          updatedAt: new Date(Date.parse('2022-08-01 00:00')),
        },
        {
          docId: 11,
          userId: 14,
          petId: 4,
          dateOfReceipt: new Date(2022, 7, 9, 11, 0),
          isClose: false,
          createdAt: new Date(Date.parse('2022-08-01 00:00')),
          updatedAt: new Date(Date.parse('2022-08-01 00:00')),
        },
        {
          docId: 11,
          userId: 14,
          petId: 5,
          dateOfReceipt: new Date(2022, 7, 9, 16, 0),
          isClose: false,
          createdAt: new Date(Date.parse('2022-08-01 00:00')),
          updatedAt: new Date(Date.parse('2022-08-01 00:00')),
        },
        {
          docId: 11,
          userId: 1,
          petId: 1,
          dateOfReceipt: new Date(2022, 7, 10, 9, 0),
          isClose: false,
          createdAt: new Date(Date.parse('2022-08-01 00:00')),
          updatedAt: new Date(Date.parse('2022-08-01 00:00')),
        },
        {
          docId: 11,
          userId: 13,
          petId: 2,
          dateOfReceipt: new Date(2022, 7, 10, 10, 0),
          isClose: false,
          createdAt: new Date(Date.parse('2022-08-01 00:00')),
          updatedAt: new Date(Date.parse('2022-08-01 00:00')),
        },
        {
          docId: 11,
          userId: 13,
          petId: 3,
          dateOfReceipt: new Date(2022, 7, 10, 10, 30),
          isClose: false,
          createdAt: new Date(Date.parse('2022-08-01 00:00')),
          updatedAt: new Date(Date.parse('2022-08-01 00:00')),
        },
        {
          docId: 11,
          userId: 14,
          petId: 4,
          dateOfReceipt: new Date(2022, 7, 10, 11, 0),
          isClose: false,
          createdAt: new Date(Date.parse('2022-08-01 00:00')),
          updatedAt: new Date(Date.parse('2022-08-01 00:00')),
        },
        {
          docId: 11,
          userId: 14,
          petId: 5,
          dateOfReceipt: new Date(2022, 7, 10, 16, 0),
          isClose: false,
          createdAt: new Date(Date.parse('2022-08-01 00:00')),
          updatedAt: new Date(Date.parse('2022-08-01 00:00')),
        },
        {
          docId: 11,
          userId: 1,
          petId: 1,
          dateOfReceipt: new Date(2022, 7, 11, 9, 0),
          isClose: false,
          createdAt: new Date(Date.parse('2022-08-01 00:00')),
          updatedAt: new Date(Date.parse('2022-08-01 00:00')),
        },
        {
          docId: 11,
          userId: 13,
          petId: 2,
          dateOfReceipt: new Date(2022, 7, 11, 10, 0),
          isClose: false,
          createdAt: new Date(Date.parse('2022-08-01 00:00')),
          updatedAt: new Date(Date.parse('2022-08-01 00:00')),
        },
        {
          docId: 11,
          userId: 13,
          petId: 3,
          dateOfReceipt: new Date(2022, 7, 11, 10, 30),
          isClose: false,
          createdAt: new Date(Date.parse('2022-08-01 00:00')),
          updatedAt: new Date(Date.parse('2022-08-01 00:00')),
        },
        {
          docId: 11,
          userId: 14,
          petId: 4,
          dateOfReceipt: new Date(2022, 7, 11, 11, 0),
          isClose: false,
          createdAt: new Date(Date.parse('2022-08-01 00:00')),
          updatedAt: new Date(Date.parse('2022-08-01 00:00')),
        },
        {
          docId: 11,
          userId: 14,
          petId: 5,
          dateOfReceipt: new Date(2022, 7, 11, 16, 0),
          isClose: false,
          createdAt: new Date(Date.parse('2022-08-01 00:00')),
          updatedAt: new Date(Date.parse('2022-08-01 00:00')),
        },
        {
          docId: 11,
          userId: 1,
          petId: 1,
          dateOfReceipt: new Date(2022, 7, 12, 9, 0),
          isClose: false,
          createdAt: new Date(Date.parse('2022-08-01 00:00')),
          updatedAt: new Date(Date.parse('2022-08-01 00:00')),
        },
        {
          docId: 11,
          userId: 13,
          petId: 2,
          dateOfReceipt: new Date(2022, 7, 12, 10, 0),
          isClose: false,
          createdAt: new Date(Date.parse('2022-08-01 00:00')),
          updatedAt: new Date(Date.parse('2022-08-01 00:00')),
        },
        {
          docId: 11,
          userId: 13,
          petId: 3,
          dateOfReceipt: new Date(2022, 7, 12, 10, 30),
          isClose: false,
          createdAt: new Date(Date.parse('2022-08-01 00:00')),
          updatedAt: new Date(Date.parse('2022-08-01 00:00')),
        },
        {
          docId: 11,
          userId: 14,
          petId: 4,
          dateOfReceipt: new Date(2022, 7, 12, 11, 0),
          isClose: false,
          createdAt: new Date(Date.parse('2022-08-01 00:00')),
          updatedAt: new Date(Date.parse('2022-08-01 00:00')),
        },
        {
          docId: 11,
          userId: 14,
          petId: 5,
          dateOfReceipt: new Date(2022, 7, 12, 16, 0),
          isClose: false,
          createdAt: new Date(Date.parse('2022-08-01 00:00')),
          updatedAt: new Date(Date.parse('2022-08-01 00:00')),
        },
        {
          docId: 11,
          userId: 1,
          petId: 1,
          dateOfReceipt: new Date(2022, 7, 15, 9, 0),
          isClose: false,
          createdAt: new Date(Date.parse('2022-08-01 00:00')),
          updatedAt: new Date(Date.parse('2022-08-01 00:00')),
        },
        {
          docId: 11,
          userId: 13,
          petId: 2,
          dateOfReceipt: new Date(2022, 7, 15, 10, 0),
          isClose: false,
          createdAt: new Date(Date.parse('2022-08-01 00:00')),
          updatedAt: new Date(Date.parse('2022-08-01 00:00')),
        },
        {
          docId: 11,
          userId: 13,
          petId: 3,
          dateOfReceipt: new Date(2022, 7, 15, 10, 30),
          isClose: false,
          createdAt: new Date(Date.parse('2022-08-01 00:00')),
          updatedAt: new Date(Date.parse('2022-08-01 00:00')),
        },
        {
          docId: 11,
          userId: 14,
          petId: 4,
          dateOfReceipt: new Date(2022, 7, 15, 11, 0),
          isClose: false,
          createdAt: new Date(Date.parse('2022-08-01 00:00')),
          updatedAt: new Date(Date.parse('2022-08-01 00:00')),
        },
        {
          docId: 11,
          userId: 14,
          petId: 5,
          dateOfReceipt: new Date(2022, 7, 15, 16, 0),
          isClose: false,
          createdAt: new Date(Date.parse('2022-08-01 00:00')),
          updatedAt: new Date(Date.parse('2022-08-01 00:00')),
        },
        {
          docId: 11,
          userId: 1,
          petId: 1,
          dateOfReceipt: new Date(2022, 7, 16, 9, 0),
          isClose: false,
          createdAt: new Date(Date.parse('2022-08-01 00:00')),
          updatedAt: new Date(Date.parse('2022-08-01 00:00')),
        },
        {
          docId: 11,
          userId: 13,
          petId: 2,
          dateOfReceipt: new Date(2022, 7, 16, 10, 0),
          isClose: false,
          createdAt: new Date(Date.parse('2022-08-01 00:00')),
          updatedAt: new Date(Date.parse('2022-08-01 00:00')),
        },
        {
          docId: 11,
          userId: 13,
          petId: 3,
          dateOfReceipt: new Date(2022, 7, 16, 10, 30),
          isClose: false,
          createdAt: new Date(Date.parse('2022-08-01 00:00')),
          updatedAt: new Date(Date.parse('2022-08-01 00:00')),
        },
        {
          docId: 11,
          userId: 14,
          petId: 4,
          dateOfReceipt: new Date(2022, 7, 16, 11, 0),
          isClose: false,
          createdAt: new Date(Date.parse('2022-08-01 00:00')),
          updatedAt: new Date(Date.parse('2022-08-01 00:00')),
        },
        {
          docId: 11,
          userId: 14,
          petId: 5,
          dateOfReceipt: new Date(2022, 7, 16, 16, 0),
          isClose: false,
          createdAt: new Date(Date.parse('2022-08-01 00:00')),
          updatedAt: new Date(Date.parse('2022-08-01 00:00')),
        },
        {
          docId: 11,
          userId: 1,
          petId: 1,
          dateOfReceipt: new Date(2022, 7, 17, 9, 0),
          isClose: false,
          createdAt: new Date(Date.parse('2022-08-01 00:00')),
          updatedAt: new Date(Date.parse('2022-08-01 00:00')),
        },
        {
          docId: 11,
          userId: 13,
          petId: 2,
          dateOfReceipt: new Date(2022, 7, 17, 10, 0),
          isClose: false,
          createdAt: new Date(Date.parse('2022-08-01 00:00')),
          updatedAt: new Date(Date.parse('2022-08-01 00:00')),
        },
        {
          docId: 11,
          userId: 13,
          petId: 3,
          dateOfReceipt: new Date(2022, 7, 17, 10, 30),
          isClose: false,
          createdAt: new Date(Date.parse('2022-08-01 00:00')),
          updatedAt: new Date(Date.parse('2022-08-01 00:00')),
        },
        {
          docId: 11,
          userId: 14,
          petId: 4,
          dateOfReceipt: new Date(2022, 7, 17, 11, 0),
          isClose: false,
          createdAt: new Date(Date.parse('2022-08-01 00:00')),
          updatedAt: new Date(Date.parse('2022-08-01 00:00')),
        },
        {
          docId: 11,
          userId: 14,
          petId: 5,
          dateOfReceipt: new Date(2022, 7, 17, 16, 0),
          isClose: false,
          createdAt: new Date(Date.parse('2022-08-01 00:00')),
          updatedAt: new Date(Date.parse('2022-08-01 00:00')),
        },
        {
          docId: 11,
          userId: 1,
          petId: 1,
          dateOfReceipt: new Date(2022, 7, 18, 9, 0),
          isClose: false,
          createdAt: new Date(Date.parse('2022-08-01 00:00')),
          updatedAt: new Date(Date.parse('2022-08-01 00:00')),
        },
        {
          docId: 11,
          userId: 13,
          petId: 2,
          dateOfReceipt: new Date(2022, 7, 18, 10, 0),
          isClose: false,
          createdAt: new Date(Date.parse('2022-08-01 00:00')),
          updatedAt: new Date(Date.parse('2022-08-01 00:00')),
        },
        {
          docId: 11,
          userId: 13,
          petId: 3,
          dateOfReceipt: new Date(2022, 7, 18, 10, 30),
          isClose: false,
          createdAt: new Date(Date.parse('2022-08-01 00:00')),
          updatedAt: new Date(Date.parse('2022-08-01 00:00')),
        },
        {
          docId: 11,
          userId: 14,
          petId: 4,
          dateOfReceipt: new Date(2022, 7, 18, 11, 0),
          isClose: false,
          createdAt: new Date(Date.parse('2022-08-01 00:00')),
          updatedAt: new Date(Date.parse('2022-08-01 00:00')),
        },
        {
          docId: 11,
          userId: 14,
          petId: 5,
          dateOfReceipt: new Date(2022, 7, 18, 16, 0),
          isClose: false,
          createdAt: new Date(Date.parse('2022-08-01 00:00')),
          updatedAt: new Date(Date.parse('2022-08-01 00:00')),
        },
        {
          docId: 11,
          userId: 1,
          petId: 1,
          dateOfReceipt: new Date(2022, 7, 19, 9, 0),
          isClose: false,
          createdAt: new Date(Date.parse('2022-08-01 00:00')),
          updatedAt: new Date(Date.parse('2022-08-01 00:00')),
        },
        {
          docId: 11,
          userId: 13,
          petId: 2,
          dateOfReceipt: new Date(2022, 7, 19, 10, 0),
          isClose: false,
          createdAt: new Date(Date.parse('2022-08-01 00:00')),
          updatedAt: new Date(Date.parse('2022-08-01 00:00')),
        },
        {
          docId: 11,
          userId: 13,
          petId: 3,
          dateOfReceipt: new Date(2022, 7, 19, 10, 30),
          isClose: false,
          createdAt: new Date(Date.parse('2022-08-01 00:00')),
          updatedAt: new Date(Date.parse('2022-08-01 00:00')),
        },
        {
          docId: 11,
          userId: 14,
          petId: 4,
          dateOfReceipt: new Date(2022, 7, 19, 11, 0),
          isClose: false,
          createdAt: new Date(Date.parse('2022-08-01 00:00')),
          updatedAt: new Date(Date.parse('2022-08-01 00:00')),
        },
        {
          docId: 11,
          userId: 14,
          petId: 5,
          dateOfReceipt: new Date(2022, 7, 19, 16, 0),
          isClose: false,
          createdAt: new Date(Date.parse('2022-08-01 00:00')),
          updatedAt: new Date(Date.parse('2022-08-01 00:00')),
        },
        {
          docId: 11,
          userId: 1,
          petId: 1,
          dateOfReceipt: new Date(2022, 7, 22, 9, 0),
          isClose: false,
          createdAt: new Date(Date.parse('2022-08-01 00:00')),
          updatedAt: new Date(Date.parse('2022-08-01 00:00')),
        },
        {
          docId: 11,
          userId: 13,
          petId: 2,
          dateOfReceipt: new Date(2022, 7, 22, 10, 0),
          isClose: false,
          createdAt: new Date(Date.parse('2022-08-01 00:00')),
          updatedAt: new Date(Date.parse('2022-08-01 00:00')),
        },
        {
          docId: 11,
          userId: 13,
          petId: 3,
          dateOfReceipt: new Date(2022, 7, 22, 10, 30),
          isClose: false,
          createdAt: new Date(Date.parse('2022-08-01 00:00')),
          updatedAt: new Date(Date.parse('2022-08-01 00:00')),
        },
        {
          docId: 11,
          userId: 14,
          petId: 4,
          dateOfReceipt: new Date(2022, 7, 22, 11, 0),
          isClose: false,
          createdAt: new Date(Date.parse('2022-08-01 00:00')),
          updatedAt: new Date(Date.parse('2022-08-01 00:00')),
        },
        {
          docId: 11,
          userId: 14,
          petId: 5,
          dateOfReceipt: new Date(2022, 7, 22, 16, 0),
          isClose: false,
          createdAt: new Date(Date.parse('2022-08-01 00:00')),
          updatedAt: new Date(Date.parse('2022-08-01 00:00')),
        },
        {
          docId: 11,
          userId: 1,
          petId: 1,
          dateOfReceipt: new Date(2022, 7, 23, 9, 0),
          isClose: false,
          createdAt: new Date(Date.parse('2022-08-01 00:00')),
          updatedAt: new Date(Date.parse('2022-08-01 00:00')),
        },
        {
          docId: 11,
          userId: 13,
          petId: 2,
          dateOfReceipt: new Date(2022, 7, 23, 10, 0),
          isClose: false,
          createdAt: new Date(Date.parse('2022-08-01 00:00')),
          updatedAt: new Date(Date.parse('2022-08-01 00:00')),
        },
        {
          docId: 11,
          userId: 13,
          petId: 3,
          dateOfReceipt: new Date(2022, 7, 23, 10, 30),
          isClose: false,
          createdAt: new Date(Date.parse('2022-08-01 00:00')),
          updatedAt: new Date(Date.parse('2022-08-01 00:00')),
        },
        {
          docId: 11,
          userId: 14,
          petId: 4,
          dateOfReceipt: new Date(2022, 7, 23, 11, 0),
          isClose: false,
          createdAt: new Date(Date.parse('2022-08-01 00:00')),
          updatedAt: new Date(Date.parse('2022-08-01 00:00')),
        },
        {
          docId: 11,
          userId: 14,
          petId: 5,
          dateOfReceipt: new Date(2022, 7, 23, 16, 0),
          isClose: false,
          createdAt: new Date(Date.parse('2022-08-01 00:00')),
          updatedAt: new Date(Date.parse('2022-08-01 00:00')),
        },
        {
          docId: 11,
          userId: 1,
          petId: 1,
          dateOfReceipt: new Date(2022, 7, 24, 9, 0),
          isClose: false,
          createdAt: new Date(Date.parse('2022-08-01 00:00')),
          updatedAt: new Date(Date.parse('2022-08-01 00:00')),
        },
        {
          docId: 11,
          userId: 13,
          petId: 2,
          dateOfReceipt: new Date(2022, 7, 24, 10, 0),
          isClose: false,
          createdAt: new Date(Date.parse('2022-08-01 00:00')),
          updatedAt: new Date(Date.parse('2022-08-01 00:00')),
        },
        {
          docId: 11,
          userId: 13,
          petId: 3,
          dateOfReceipt: new Date(2022, 7, 24, 10, 30),
          isClose: false,
          createdAt: new Date(Date.parse('2022-08-01 00:00')),
          updatedAt: new Date(Date.parse('2022-08-01 00:00')),
        },
        {
          docId: 11,
          userId: 14,
          petId: 4,
          dateOfReceipt: new Date(2022, 7, 24, 11, 0),
          isClose: false,
          createdAt: new Date(Date.parse('2022-08-01 00:00')),
          updatedAt: new Date(Date.parse('2022-08-01 00:00')),
        },
        {
          docId: 11,
          userId: 14,
          petId: 5,
          dateOfReceipt: new Date(2022, 7, 24, 16, 0),
          isClose: false,
          createdAt: new Date(Date.parse('2022-08-01 00:00')),
          updatedAt: new Date(Date.parse('2022-08-01 00:00')),
        },
        {
          docId: 11,
          userId: 1,
          petId: 1,
          dateOfReceipt: new Date(2022, 7, 25, 9, 0),
          isClose: false,
          createdAt: new Date(Date.parse('2022-08-01 00:00')),
          updatedAt: new Date(Date.parse('2022-08-01 00:00')),
        },
        {
          docId: 11,
          userId: 13,
          petId: 2,
          dateOfReceipt: new Date(2022, 7, 25, 10, 0),
          isClose: false,
          createdAt: new Date(Date.parse('2022-08-01 00:00')),
          updatedAt: new Date(Date.parse('2022-08-01 00:00')),
        },
        {
          docId: 11,
          userId: 13,
          petId: 3,
          dateOfReceipt: new Date(2022, 7, 25, 10, 30),
          isClose: false,
          createdAt: new Date(Date.parse('2022-08-01 00:00')),
          updatedAt: new Date(Date.parse('2022-08-01 00:00')),
        },
        {
          docId: 11,
          userId: 14,
          petId: 4,
          dateOfReceipt: new Date(2022, 7, 25, 11, 0),
          isClose: false,
          createdAt: new Date(Date.parse('2022-08-01 00:00')),
          updatedAt: new Date(Date.parse('2022-08-01 00:00')),
        },
        {
          docId: 11,
          userId: 14,
          petId: 5,
          dateOfReceipt: new Date(2022, 7, 25, 16, 0),
          isClose: false,
          createdAt: new Date(Date.parse('2022-08-01 00:00')),
          updatedAt: new Date(Date.parse('2022-08-01 00:00')),
        },
        {
          docId: 11,
          userId: 1,
          petId: 1,
          dateOfReceipt: new Date(2022, 7, 26, 9, 0),
          isClose: false,
          createdAt: new Date(Date.parse('2022-08-01 00:00')),
          updatedAt: new Date(Date.parse('2022-08-01 00:00')),
        },
        {
          docId: 11,
          userId: 13,
          petId: 2,
          dateOfReceipt: new Date(2022, 7, 26, 10, 0),
          isClose: false,
          createdAt: new Date(Date.parse('2022-08-01 00:00')),
          updatedAt: new Date(Date.parse('2022-08-01 00:00')),
        },
        {
          docId: 11,
          userId: 13,
          petId: 3,
          dateOfReceipt: new Date(2022, 7, 26, 10, 30),
          isClose: false,
          createdAt: new Date(Date.parse('2022-08-01 00:00')),
          updatedAt: new Date(Date.parse('2022-08-01 00:00')),
        },
        {
          docId: 11,
          userId: 14,
          petId: 4,
          dateOfReceipt: new Date(2022, 7, 26, 11, 0),
          isClose: false,
          createdAt: new Date(Date.parse('2022-08-01 00:00')),
          updatedAt: new Date(Date.parse('2022-08-01 00:00')),
        },
        {
          docId: 11,
          userId: 14,
          petId: 5,
          dateOfReceipt: new Date(2022, 7, 26, 16, 0),
          isClose: false,
          createdAt: new Date(Date.parse('2022-08-01 00:00')),
          updatedAt: new Date(Date.parse('2022-08-01 00:00')),
        },
        {
          docId: 11,
          userId: 1,
          petId: 1,
          dateOfReceipt: new Date(2022, 7, 29, 9, 0),
          isClose: false,
          createdAt: new Date(Date.parse('2022-08-01 00:00')),
          updatedAt: new Date(Date.parse('2022-08-01 00:00')),
        },
        {
          docId: 11,
          userId: 13,
          petId: 2,
          dateOfReceipt: new Date(2022, 7, 29, 10, 0),
          isClose: false,
          createdAt: new Date(Date.parse('2022-08-01 00:00')),
          updatedAt: new Date(Date.parse('2022-08-01 00:00')),
        },
        {
          docId: 11,
          userId: 13,
          petId: 3,
          dateOfReceipt: new Date(2022, 7, 29, 10, 30),
          isClose: false,
          createdAt: new Date(Date.parse('2022-08-01 00:00')),
          updatedAt: new Date(Date.parse('2022-08-01 00:00')),
        },
        {
          docId: 11,
          userId: 14,
          petId: 4,
          dateOfReceipt: new Date(2022, 7, 29, 11, 0),
          isClose: false,
          createdAt: new Date(Date.parse('2022-08-01 00:00')),
          updatedAt: new Date(Date.parse('2022-08-01 00:00')),
        },
        {
          docId: 11,
          userId: 14,
          petId: 5,
          dateOfReceipt: new Date(2022, 7, 29, 16, 0),
          isClose: false,
          createdAt: new Date(Date.parse('2022-08-01 00:00')),
          updatedAt: new Date(Date.parse('2022-08-01 00:00')),
        },
        {
          docId: 11,
          userId: 1,
          petId: 1,
          dateOfReceipt: new Date(2022, 7, 30, 9, 0),
          isClose: false,
          createdAt: new Date(Date.parse('2022-08-01 00:00')),
          updatedAt: new Date(Date.parse('2022-08-01 00:00')),
        },
        {
          docId: 11,
          userId: 13,
          petId: 2,
          dateOfReceipt: new Date(2022, 7, 30, 10, 0),
          isClose: false,
          createdAt: new Date(Date.parse('2022-08-01 00:00')),
          updatedAt: new Date(Date.parse('2022-08-01 00:00')),
        },
        {
          docId: 11,
          userId: 13,
          petId: 3,
          dateOfReceipt: new Date(2022, 7, 30, 10, 30),
          isClose: false,
          createdAt: new Date(Date.parse('2022-08-01 00:00')),
          updatedAt: new Date(Date.parse('2022-08-01 00:00')),
        },
        {
          docId: 11,
          userId: 14,
          petId: 4,
          dateOfReceipt: new Date(2022, 7, 30, 11, 0),
          isClose: false,
          createdAt: new Date(Date.parse('2022-08-01 00:00')),
          updatedAt: new Date(Date.parse('2022-08-01 00:00')),
        },
        {
          docId: 11,
          userId: 14,
          petId: 5,
          dateOfReceipt: new Date(2022, 7, 30, 16, 0),
          isClose: false,
          createdAt: new Date(Date.parse('2022-08-01 00:00')),
          updatedAt: new Date(Date.parse('2022-08-01 00:00')),
        },
        {
          docId: 11,
          userId: 1,
          petId: 1,
          dateOfReceipt: new Date(2022, 7, 31, 9, 0),
          isClose: false,
          createdAt: new Date(Date.parse('2022-08-01 00:00')),
          updatedAt: new Date(Date.parse('2022-08-01 00:00')),
        },
        {
          docId: 11,
          userId: 13,
          petId: 2,
          dateOfReceipt: new Date(2022, 7, 31, 10, 0),
          isClose: false,
          createdAt: new Date(Date.parse('2022-08-01 00:00')),
          updatedAt: new Date(Date.parse('2022-08-01 00:00')),
        },
        {
          docId: 11,
          userId: 13,
          petId: 3,
          dateOfReceipt: new Date(2022, 7, 31, 10, 30),
          isClose: false,
          createdAt: new Date(Date.parse('2022-08-01 00:00')),
          updatedAt: new Date(Date.parse('2022-08-01 00:00')),
        },
        {
          docId: 11,
          userId: 14,
          petId: 4,
          dateOfReceipt: new Date(2022, 7, 31, 11, 0),
          isClose: false,
          createdAt: new Date(Date.parse('2022-08-01 00:00')),
          updatedAt: new Date(Date.parse('2022-08-01 00:00')),
        },
        {
          docId: 11,
          userId: 14,
          petId: 5,
          dateOfReceipt: new Date(2022, 7, 31, 16, 0),
          isClose: false,
          createdAt: new Date(Date.parse('2022-08-01 00:00')),
          updatedAt: new Date(Date.parse('2022-08-01 00:00')),
        },
      ],
    });
  } catch (e) {
    if (e instanceof Error) {
      console.log(e.message);
    }
    process.exit(1);
  } finally {
    await prisma.$disconnect();
  }
};

load();
